services:
  - type: web
    name: shygyn-bot
    runtime: python
    region: frankfurt  # опционально, выбери ближайший регион
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false